NSString *NSStringFromUIDeviceOrientation(UIDeviceOrientation orientation);
NSString *NSStringFromUIInterfaceOrientation(UIInterfaceOrientation orientation);
CGAffineTransform CGAffineTransformFromUIOrientation(UIInterfaceOrientation orientation);